/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class j_java_cpp */

#ifndef _Included_j_java_cpp
#define _Included_j_java_cpp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     j_java_cpp
 * Method:    speech
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_j_java_1cpp_speech
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     j_java_cpp
 * Method:    speech1
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_j_java_1cpp_speech1
  (JNIEnv *, jclass, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
