/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_cpp */

#ifndef _Included_java_cpp
#define _Included_java_cpp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_cpp
 * Method:    speech
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_java_1cpp_speech
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
